### ISSUE TITLE
Missing dependency?

### ISSUE THREAD

**Issue by paddleman** [marcioj/ember-cli-scaffold#17]
Received the following error when running ember g scaffold ..........

Cannot find module 'chalk'  ...........etc etc

Problem was fixed with a manual install 

npm install --save-dev chalk

Thanks for the addon.

**Comment by marcioj** [comment]
Hi @paddleman thanks for report this issue.
Can you show what is your ember-cli, npm, node, and ember-cli-scaffold versions?

**Comment by marcioj** [comment]
I found the issue, the chalk version was being used in the wrong place. I fixed in #19 and published a new version `0.1.1` and now it's working.
I'm closing this issue feel free to reopen if you hit it again.

Thanks!
