### ISSUE TITLE
Option to disable fixtures

### ISSUE THREAD

**Issue by kevintraver** [marcioj/ember-cli-scaffold#20]
It would be nice to have the option to disable generating fixtures. When using an adapter, it still generates fixtures, which causes errors when trying to use a backend.

Thanks!

**Comment by marcioj** [comment]
Hi @kevintraver I'm working in remove the fixtures and the ember data FixtureAdapter since it's deprecated, and instead use https://github.com/samselikoff/ember-cli-mirage which is the best approach to mock data in tests.

**Comment by kevintraver** [comment]
Ok, thanks!
