### ISSUE TITLE
The import for the save-model-mixin path is incorrect when using pods

### ISSUE THREAD

**Issue by robbyoconnor** [marcioj/ember-cli-scaffold#23]

**Comment by marcioj** [comment]
Hi @robbyoconnor thanks for open the issue.
Are you using the `podModulePrefix` option?

**Comment by robbyoconnor** [comment]
Yes.

**Comment by robbyoconnor** [comment]
I manually fixed this but don't have enough experience to fix it

**Comment by marcioj** [comment]
Released v1.1.1 with the fix, let me know if you hit this issue again.

**Comment by robbyoconnor** [comment]
It's not on npm yet?

**Comment by marcioj** [comment]
Whoops I forgot to run npm publish. It's available now https://www.npmjs.com/package/ember-cli-scaffold

**Comment by robbyoconnor** [comment]
:+1:
