### ISSUE TITLE
Bring up to date with current best practices

### ISSUE THREAD

**Issue by pablobm** [marcioj/ember-cli-scaffold#26]
Lately I have been doing some research on building CRUD interfaces with Ember. It started as a couple of notes, and it quickly developed into a long list of design/implementation decisions that I've been keeping here: https://gist.github.com/pablobm/e77a98e5f3c610953a82 It's still a work in progress.

From my background as a Rails developer, I love the idea of using scaffolds as a way to communicate what best practices are. I think this addon could be a great help there. However, there are some details I think should change to reflect the current conventions in the Ember community.

I have already started doing some work on this, see pull request #25. I'm happy to continue and create new PRs to implement my ideas on the gist. Do you have any thoughts?

**Comment by marcioj** [comment]
Hi @pablobm, I'm also a rails developer and when I started with rails a time ago used the scaffold generator to better understand the "rails way". This project has the same idea: creates a basic CRUD using the default ember stack. So beginners can see what is the basic API needed to get things done. I read your gist and agree with your ideas. Thanks for the research!

**Comment by marcioj** [comment]
I'm closing this issue but feel free to send the PR's with your other suggestions.

**Comment by pablobm** [comment]
Great stuff. Will do 👍
