### ISSUE TITLE
How can destroy/remove a scaffold?

### ISSUE THREAD

**Issue by jgamedev** [marcioj/ember-cli-scaffold#30]
http://thegoodhuman.com/please-just-clean-up-after-yourself/

**Comment by marcioj** [comment]
ember-cli has a command called `destroy` which is the opposite of `generate`.
So, if you generate something with `ember generate scaffold user name:string` just calls `ember destroy scaffold user name:string` and the previous changes will be undone.

**Comment by jgamedev** [comment]
Thanks, maybe add this to the Read me file so that people don't wonder so much?
Btw, Google doesnt help much in this case because it doesn't bring this information up and most results actually refer to Rails scaffold

**Comment by marcioj** [comment]
@jgamedev it makes sense. I added in f762e957796dc5ea654755334a5d59fed50c11ed

**Comment by jgamedev** [comment]
Thank you.
Although I'd be surprised if you'd need to provide more than just the model name to issue a destroy command, not the all the original params as per your example. ( but can't tell for sure)

**Comment by marcioj** [comment]
You're right, just `ember destroy scaffold <model-name>` works. I updated the README again with this simplified version.
