### ISSUE TITLE
Edit view not working

### ISSUE THREAD

**Issue by AlexCppns** [marcioj/ember-cli-scaffold#5]
when I look at the edit view, the form is not prefilled. Is there code to write to get the model data?

Edit: I made sure in the inspector that the model was loaded, it s not not showing up in the form..

**Comment by marcioj** [comment]
Hi @AlexCppns, can you describe how you used the `ember g scaffold` command? Also, are you using the pods structure? Thanks.

**Comment by AlexCppns** [comment]
I did this:

```
ember generate scaffold creative name:string click_url:string 
```

and I answered `no` when it asked me if I wanted to overwrite the creative model. I then had to load the model instance manually in the edit route since it did not exist:

```
import Ember from 'ember';
import SaveModelMixin from '../../mixins/save-model-mixin';

export default Ember.Route.extend(SaveModelMixin, {
 model: function(params) {
   this.store.find('creative',  params.creative_id)
 }
});

```

my creative model file:

```
import DS from 'ember-data';

export default DS.Model.extend({
  name: DS.attr('string'),
  status: DS.attr('string'),
  click_url: DS.attr('string'),
  dimensions: DS.attr('string'),
  image_preview: DS.attr('string'),
  created_at: DS.attr('date'),
  creative_type: DS.attr('string')
});
```

**Comment by marcioj** [comment]
I have tried to reproduce your problem, but have had no success. Did you receive some error in the browser console?

**Comment by AlexCppns** [comment]
I noticed I forgot a 'return' statement in the model method in my routes. I did have to write that model method after the fact to make it work. Now I am trying to submit the form and it's doing a PUT in /creatives (which returns a 404), I am not sure why... it should pass the id of the creative instance.

**Comment by AlexCppns** [comment]
Do I need ember-localstorage-adapter for it to work?

**Comment by AlexCppns** [comment]
Closing as I solved it.

**Comment by marcioj** [comment]
Sorry for the delay @AlexCppns. Yes, ember-cli-scaffold doesn't include any adapter in the moment. I intend to use https://github.com/samselikoff/ember-pretenderify to get things working in development and test using the RESTAdapter. In the meanwhile you can use the localstorage adapter.
