### ISSUE TITLE
[FEATURE] Not providing a type should default to 'string'

### ISSUE THREAD

**Issue by kalmanh** [marcioj/ember-cli-scaffold#8]
Would be nice if

$ember g scaffold person name 

generated DS.attr('string') This is how Rails does it - the assumption being that most things out there are strtings. If you don't specify a type - it defaults to 'string'. Currently, an empty type is assumed. If you can point me in the right direction where this is - I can probably PR this.

**Comment by marcioj** [comment]
Hi @kalmanh there is a slight difference between rails and ember-cli in this case.
For ember-data, when not supplying a type for `DS.attr()`, it will just not use any transform and pass the raw value. But `DS.attr('string')` uses the `DS.StringTransform`. So I think we have to keep this semantic.
In fact when generating the model `ember g scaffold args` just [delegates](https://github.com/marcioj/ember-cli-scaffold/blob/master/blueprints/scaffold/index.js#L37) to `ember g model args` which is using `DS.attr()` when no type is provided for some field.
